name: build
on:
  pull_request:
  push:
    branches:
    - master
jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - uses: borales/actions-yarn@v4
      with:
        cmd: install
    - run: node ./build.mjs build-prod